# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4808bbae9d607bcc4a9660108eaf1ad27286c47676ed54297668671af08743c0ec836f7d04a9525336606017a7d0fdf9e6acf9bd87d69f5f124ec886e20966b8

test:
  secret_key_base: c6dc6c4a3ac828c3cd57c251481591e3f78473ef3086fc398d6eb900c2005d53f668450b0fe27512c4b9c390d4bff796f45da0c8748ccecbfef36292e5888903

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  google_analytics_code: YOUR CODE HERE
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>